#ifndef TOY_RENDERER_3D_CONFIG_H
#define TOY_RENDERER_3D_CONFIG_H

#define SCREEN_W 800
#define SCREEN_H 800
#define TITLE "3D Toy Renderer"

#define FOREGROUND_COLOR GREEN
#define BACKGROUND_COLOR BLACK

#endif
